import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import dynamic from "next/dynamic";
import NoiseSVG from "@/components/noise-svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Development",
  description: "Generated by create next app",
};

const DynamicScrollToTop = dynamic(() => import("@/components/scroll-to-top"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NoiseSVG />
        <Navbar />
        {children}
        <Footer />
        <DynamicScrollToTop />
      </body>
    </html>
  );
}
